[package]
name = "traveling-salesman"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
clap = { version = "4.5.47", features = ["derive"] }
lazy_static = "1.5.0"
actix-web = "4"
actix-cors = "=0.7.1"
